(in-package #:clifford/test)

(nst:def-test-group predicates-tests ()
  (nst:def-test can-zerop (:values :true (:not :true) (:not :true))
    (values (zerop (make-r2))
            (zerop (make-r2 :one 1))
            (zerop (make-r2 :xy 1))))

  (nst:def-test can-= (:values :true :true :true (:not :true) (:not :true))
    (values (= (make-r2 :one 1 :x 2 :y 3 :xy 4)
               (make-r2 :one 1 :x 2 :y 3 :xy 4))
            (= (make-r2 :one 1) 1)
            (= 1 (make-r2 :one 1))
            (= 1 (make-r2 :one 1 :x 1))
            (= (make-r2 :one 1 :x 1) (make-r2 :one 1 :y 1))))

  (nst:def-test can-/= (:values :true :true :true :true :true (:not :true))
    (values (/= (make-r2 :one 1 :x 2 :y 3 :xy 4)
                (make-r2 :one 1 :x 2))
            (/= (make-r2 :one 1) 2)
            (/= 2 (make-r2 :one 1))
            (/= 1 (make-r2 :one 1 :x 1))
            (/= (make-r2 :one 1 :x 1) (make-r2 :one 1 :y 1))
            (/= (make-r2 :one 1 :x 2 :y 3 :xy 4)
                (make-r2 :one 1 :x 2 :y 3 :xy 4)))))
